#ifndef NANOTUBE_LWIPOPTS_H
#define NANOTUBE_LWIPOPTS_H

#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define LWIP_PROVIDE_ERRNO 1
#define NO_SYS 1
#define LWIP_DHCP 1
#define LWIP_DNS 0
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_STATS 0
#define LWIP_TCPIP_CORE_LOCKING 0
#define LWIP_NOASSERT 0
#define PPP_SUPPORT 0

#endif //NANOTUBE_LWIPOPTS_H
