#ifndef NANOTUBE_LWIPOPTS_H
#define NANOTUBE_LWIPOPTS_H

#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define LWIP_PROVIDE_ERRNO 1
#define NO_SYS 1
#define LWIP_DHCP 0
#define LWIP_DNS 1
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_STATS 0
#define LWIP_TCPIP_CORE_LOCKING 0
#define LWIP_NOASSERT
#define PPP_SUPPORT 0
#define LWIP_DEBUG_TIMERNAMES 0
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_DEBUG 1
#define DHCP_DEBUG LWIP_DBG_ON

#endif //NANOTUBE_LWIPOPTS_H
